//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdGolfTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NerdGolfTrackerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NerdGolfTrackerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NerdGolfTracker.NerdGolfTrackerResources", typeof(NerdGolfTrackerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bringt Dich zum naechsten Loch..
        /// </summary>
        public static string LochwechselBefehl_Erklaerung_bringt_Dich_zum_naechsten_Loch_ {
            get {
                return ResourceManager.GetString("LochwechselBefehl_Erklaerung_bringt_Dich_zum_naechsten_Loch_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaehlt einen Schlag..
        /// </summary>
        public static string SchlagBefehl_Erklaerung_zaehlt_einen_Schlag_ {
            get {
                return ResourceManager.GetString("SchlagBefehl_Erklaerung_zaehlt_einen_Schlag_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beendet das Spiel..
        /// </summary>
        public static string SpielendeBefehl_Erklaerung_beendet_das_Spiel_ {
            get {
                return ResourceManager.GetString("SpielendeBefehl_Erklaerung_beendet_das_Spiel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zeigt das Gesamtergebnis an..
        /// </summary>
        public static string ZeigeErgebnisBefehl_Erklaerung_zeigt_das_Gesamtergebnis_an_ {
            get {
                return ResourceManager.GetString("ZeigeErgebnisBefehl_Erklaerung_zeigt_das_Gesamtergebnis_an_", resourceCulture);
            }
        }
    }
}
